export const COUNTRIES: { [key: string]: string } = {
    "": "No Flag",
    "DZ": "Algeria",
    "AU": "Australia",
    "BE": "Belgium",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "CA": "Canada",
    "CN": "China",
    "HR": "Croatia",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "EG": "Egypt",
    "EE": "Estonia",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GR": "Greece",
    "HU": "Hungary",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JP": "Japan",
    "KE": "Kenya",
    "LV": "Latvia",
    "LT": "Lithuania",
    "MT": "Malta",
    "MX": "Mexico",
    "MA": "Morocco",
    "NL": "Netherlands",
    "NG": "Nigeria",
    "NO": "Norway",
    "PK": "Pakistan",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "RO": "Romania",
    "RU": "Russia",
    "SA": "Saudi Arabia",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "ZA": "South Africa",
    "KR": "South Korea",
    "ES": "Spain",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TN": "Tunisia",
    "TR": "Turkey",
    "AE": "UAE",
    "GB": "United Kingdom",
    "US": "United States"
};
